//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BMSPhase2Demo.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Entitlement.
        /// </summary>
        public static string AddEntitlement {
            get {
                return ResourceManager.GetString("AddEntitlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        public static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Enroll.
        /// </summary>
        public static string AssociationEnroll {
            get {
                return ResourceManager.GetString("AssociationEnroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank .
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Branch.
        /// </summary>
        public static string BankBranch {
            get {
                return ResourceManager.GetString("BankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGAPMEA License No.
        /// </summary>
        public static string BGAPMEALicenseNo {
            get {
                return ResourceManager.GetString("BGAPMEALicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGAPMEA Members.
        /// </summary>
        public static string BGAPMEAMembers {
            get {
                return ResourceManager.GetString("BGAPMEAMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond.
        /// </summary>
        public static string Bond {
            get {
                return ResourceManager.GetString("Bond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond Applicants.
        /// </summary>
        public static string BondApplicants {
            get {
                return ResourceManager.GetString("BondApplicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond Area.
        /// </summary>
        public static string BondArea {
            get {
                return ResourceManager.GetString("BondArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond Category.
        /// </summary>
        public static string BondCategory {
            get {
                return ResourceManager.GetString("BondCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond Circle.
        /// </summary>
        public static string BondCircle {
            get {
                return ResourceManager.GetString("BondCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond Division.
        /// </summary>
        public static string BondDivision {
            get {
                return ResourceManager.GetString("BondDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond Entitlement.
        /// </summary>
        public static string BondEntitlement {
            get {
                return ResourceManager.GetString("BondEntitlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonder.
        /// </summary>
        public static string Bonder {
            get {
                return ResourceManager.GetString("Bonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonder Lien Bank.
        /// </summary>
        public static string BonderLienBank {
            get {
                return ResourceManager.GetString("BonderLienBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonder Product.
        /// </summary>
        public static string BonderProduct {
            get {
                return ResourceManager.GetString("BonderProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonder Raw Material.
        /// </summary>
        public static string BonderRawMaterial {
            get {
                return ResourceManager.GetString("BonderRawMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonders.
        /// </summary>
        public static string Bonders {
            get {
                return ResourceManager.GetString("Bonders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond License No.
        /// </summary>
        public static string BondLicenseNo {
            get {
                return ResourceManager.GetString("BondLicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond Registration.
        /// </summary>
        public static string BondRegistration {
            get {
                return ResourceManager.GetString("BondRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond Renewal.
        /// </summary>
        public static string BondRenewal {
            get {
                return ResourceManager.GetString("BondRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond Status.
        /// </summary>
        public static string BondStatus {
            get {
                return ResourceManager.GetString("BondStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond Sub Category.
        /// </summary>
        public static string BondSubCategory {
            get {
                return ResourceManager.GetString("BondSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond Type.
        /// </summary>
        public static string BondType {
            get {
                return ResourceManager.GetString("BondType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate/Head Office.
        /// </summary>
        public static string CorporateHeadOffice {
            get {
                return ResourceManager.GetString("CorporateHeadOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        public static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entitlement.
        /// </summary>
        public static string Entitlement {
            get {
                return ResourceManager.GetString("Entitlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entitlement Details.
        /// </summary>
        public static string EntitlementDetails {
            get {
                return ResourceManager.GetString("EntitlementDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry.
        /// </summary>
        public static string Expiry {
            get {
                return ResourceManager.GetString("Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Product.
        /// </summary>
        public static string FinishedProduct {
            get {
                return ResourceManager.GetString("FinishedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Applicants.
        /// </summary>
        public static string ListOfApplicants {
            get {
                return ResourceManager.GetString("ListOfApplicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Bonders.
        /// </summary>
        public static string ListOfBonders {
            get {
                return ResourceManager.GetString("ListOfBonders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Entitlement.
        /// </summary>
        public static string ListOfEntitlement {
            get {
                return ResourceManager.GetString("ListOfEntitlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing.
        /// </summary>
        public static string Manufacturing {
            get {
                return ResourceManager.GetString("Manufacturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing Unit Information.
        /// </summary>
        public static string ManufacturingUnitInformation {
            get {
                return ResourceManager.GetString("ManufacturingUnitInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials Group.
        /// </summary>
        public static string MaterialGroup {
            get {
                return ResourceManager.GetString("MaterialGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Unit.
        /// </summary>
        public static string MeasurementUnit {
            get {
                return ResourceManager.GetString("MeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of The Bonder.
        /// </summary>
        public static string NameOfTheBonder {
            get {
                return ResourceManager.GetString("NameOfTheBonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of The Manufacturing Unit.
        /// </summary>
        public static string NameOfTheManufacturingUnit {
            get {
                return ResourceManager.GetString("NameOfTheManufacturingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premises.
        /// </summary>
        public static string Premises {
            get {
                return ResourceManager.GetString("Premises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond Module System.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upazila.
        /// </summary>
        public static string Upazila {
            get {
                return ResourceManager.GetString("Upazila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Entitlement.
        /// </summary>
        public static string ViewEntitlement {
            get {
                return ResourceManager.GetString("ViewEntitlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Bond Module System.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
