//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class APPUSER
    {
        public APPUSER()
        {
            this.USERPERMISSIONs = new HashSet<USERPERMISSION>();
        }
    
        public short ID { get; set; }
        [Required(ErrorMessage = "Please Enter Your Username")]
        [Display(Name = "User Name")]
        public string USERNAME { get; set; }
        [Required(ErrorMessage = "Please Enter Your Password")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        
        public string PASSWARD { get; set; }
        public string SALT { get; set; }
          [Display(Name = "First Name")]
        public string FIRSTNAME { get; set; }
          [Display(Name = "Last Name")]
        public string LASTNAME { get; set; }
        [Display(Name = "Email Address")]
        [Required(ErrorMessage = "Please Enter Your Email Address")]
        [EmailAddress(ErrorMessage = "Wrong Email Format")]
        public string EMAIL { get; set; }
        [RegularExpression(@"^\d+$", ErrorMessage = "Please Enter a Valid Phone Number")]
        [Required(ErrorMessage = "Please Enter Your Phone Number")]
        [DisplayName("Phone no")]
        public string PHONE { get; set; }
          [Display(Name = "Address")]
        public string ADDRESS { get; set; }
         [Display(Name = "Status")]
        public short ISACTIVE { get; set; }
        [Display(Name = "Last Login")]
        public Nullable<System.DateTime> LASTLOGIN { get; set; }
    
        public virtual ICollection<USERPERMISSION> USERPERMISSIONs { get; set; }
    }
}
