//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BACKTOBACKLC
    {
        public BACKTOBACKLC()
        {
            this.BACKTOBACKPRODUCTs = new List<BACKTOBACKPRODUCT>();
            this.EXBONDBACKTOBACKs = new List<EXBONDBACKTOBACK>();
        }
    
        public short ID { get; set; }

        [Display(Name = "Buyers Name")]
        [Required(ErrorMessage = "Buyers Name is required.")]
        public string BUYERSNAME { get; set; }

        [Display(Name = "Buyers Address")]
        [Required(ErrorMessage = "Buyers Address is required.")]
        public string BUYERSADDRESS { get; set; }

        [Display(Name = "LC No")]
        [Required(ErrorMessage = "LC No is required.")]
        public string LCNUMBER { get; set; }

        [Display(Name = "LC Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime LCDATE { get; set; }

        [Display(Name = "Buyers Bank")]
        [Required(ErrorMessage = "Bank Name is required.")]
        public short BUYERSBANKID { get; set; }

        [Display(Name = "Buyers Bank Branch")]
        [Required(ErrorMessage = "Branch Name is required.")]
        public short BUYERSBANKBRANCHID { get; set; }

        [Display(Name = "Shipping Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        [Required(ErrorMessage = "Shipping Date is required.")]
        public Nullable<System.DateTime> SHIPPINGDATE { get; set; }

        [Display(Name = "Correction Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> CORRECTIONDATE { get; set; }

        [Display(Name = "Product Quantity")]
        [Required(ErrorMessage = "Product Quantity is required.")]
        public Nullable<decimal> PRODUCTQUANTITY { get; set; }

        [Display(Name = "Quantity Unit")]
        [Required(ErrorMessage = "Quantity Unit is required.")]
        public string QUANTITYUNIT { get; set; }

        [Display(Name = "LC Used Price")]
        [Required(ErrorMessage = "LC user price is required.")]
        public Nullable<decimal> LCUSEDPRICE { get; set; }

        [Display(Name = "Price Unit")]
        [Required(ErrorMessage = "Price Unit is required.")]
        public string PRICEUNIT { get; set; }

        [Display(Name = "Master LC No")]
        [Required(ErrorMessage = "Master LC No is required.")]
        public string MASTERLCNUMBER { get; set; }

        [Display(Name = "Master Correction Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        [Required(ErrorMessage = "Master Correction Date is required.")]
        public System.DateTime MASTERLCCORRECTIONDATE { get; set; }

        [Display(Name = "UD No")]
        [Required(ErrorMessage = "UD No is required.")]
        public string UDNUMBER { get; set; }

        [Display(Name = "UD Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        [Required(ErrorMessage = "UD Date is required.")]
        public System.DateTime UDDATE { get; set; }

        [Display(Name = "UD Correction Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> UDCORRECTIONDATE { get; set; }

        [Display(Name = "UD Production Details")]
        public string UDPRODUCTDETAIL { get; set; }

        [Display(Name = "Bonder")]
        [Required(ErrorMessage = "Bonder Name is required.")]
        public int BONDERID { get; set; }


        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
    
        public virtual IList<BACKTOBACKPRODUCT> BACKTOBACKPRODUCTs { get; set; }
        public virtual IList<EXBONDBACKTOBACK> EXBONDBACKTOBACKs { get; set; }
        public virtual BANKBRANCH BANKBRANCH { get; set; }
        public virtual BANK BANK { get; set; }
        public virtual BONDER BONDER { get; set; }

        public bool IsSelected { get; set; }
    }
}
