//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BANK
    {
        public BANK()
        {
            this.BACKTOBACKLCs = new HashSet<BACKTOBACKLC>();
            this.BONDERLIENBANKs = new HashSet<BONDERLIENBANK>();
            this.BANKBRANCHes = new HashSet<BANKBRANCH>();
        }
    
        public short BANKSLNO { get; set; }

        [Display(Name = "Buyers Bank Name")]
        [Required ]
        public string BANKNAME { get; set; }
        public string BANKNAMEBG { get; set; }
        public string SWIFT { get; set; }
        
        [Required(ErrorMessage = "Please Enter Your Email Address")]
        [EmailAddress(ErrorMessage = "Wrong Email Format")]
        public string WEB { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual ICollection<BACKTOBACKLC> BACKTOBACKLCs { get; set; }
        public virtual ICollection<BONDERLIENBANK> BONDERLIENBANKs { get; set; }
        public virtual ICollection<BANKBRANCH> BANKBRANCHes { get; set; }
    }
}
