//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BANKBRANCH
    {
        public BANKBRANCH()
        {
            this.BACKTOBACKLCs = new HashSet<BACKTOBACKLC>();
            this.INSTALLEDMACHINEINFOes = new HashSet<INSTALLEDMACHINEINFO>();
            this.BONDERLIENBANKs = new HashSet<BONDERLIENBANK>();
        }
    
        public short BBRANCHSLNO { get; set; }
        public Nullable<short> BANKSLNO { get; set; }
	    [Display(Name = "Address")]
        [Required]
        public string BRANCHNAME { get; set; }
        public string BRANCHNAMEBG { get; set; }
        public string ADDRESS { get; set; }
        public string ADDRESSBG { get; set; }
        public string PHONE { get; set; }
        public string PHONEBG { get; set; }
        public string FAX { get; set; }
        public string FAXBG { get; set; }     
        [EmailAddress(ErrorMessage = "Wrong Email Format")]
        public string EMAIL { get; set; }
        public string OTHER { get; set; }
        public string OTHERBG { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual ICollection<BACKTOBACKLC> BACKTOBACKLCs { get; set; }
        public virtual BANK BANK { get; set; }
        public virtual ICollection<INSTALLEDMACHINEINFO> INSTALLEDMACHINEINFOes { get; set; }
        public virtual ICollection<BONDERLIENBANK> BONDERLIENBANKs { get; set; }
    }
}
