//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONDERANNUALENTITLEMENT
    {
        public short AESLNO { get; set; }
        public int BONDERSLNO { get; set; }
        public Nullable<short> BSNO { get; set; }
        public string ENTLTYPE { get; set; }
        public Nullable<decimal> TOTALSTORAGEQTY { get; set; }
        public Nullable<short> TSMUSLNO { get; set; }
        public string TOTALSTORAGEQTYEN { get; set; }
        public string TOTALSTORAGEQTYBG { get; set; }
        public Nullable<decimal> ONETIMESTORAGEQTY { get; set; }
        public Nullable<short> OTMUSLNO { get; set; }
        public string ONETIMESTORAGEQTYEN { get; set; }
        public string ONETIMESTORAGEQTYBG { get; set; }
        public Nullable<decimal> ENTITLEPERCENTQTY { get; set; }
        public Nullable<short> ETMUSLNO { get; set; }
        public string ENTITLEPERCENTEN { get; set; }
        public string ENTITLEPERCENTBG { get; set; }
        public Nullable<System.DateTime> ENTITLEFROM { get; set; }
        public Nullable<System.DateTime> ENTITLETO { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<decimal> PERCENTVAL { get; set; }
        public string STATUS { get; set; }
    
        public virtual BONDER BONDER { get; set; }
        public virtual MEASUREMENTUNIT MEASUREMENTUNIT { get; set; }
        public virtual MEASUREMENTUNIT MEASUREMENTUNIT1 { get; set; }
        public virtual MEASUREMENTUNIT MEASUREMENTUNIT2 { get; set; }
        public virtual BONDSTATU BONDSTATU { get; set; }
    }
}
