//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BONDSTATU
    {
        public BONDSTATU()
        {
            this.ASSOCIATIONENROLLs = new HashSet<ASSOCIATIONENROLL>();
            this.BONDAPPLICATIONPROGRESSes = new HashSet<BONDAPPLICATIONPROGRESS>();
            this.BONDERANNUALENTITLEMENTs = new HashSet<BONDERANNUALENTITLEMENT>();
        }
        
        public short BSNO { get; set; }
        public int BONDERSLNO { get; set; }
        public string REFNO { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> BSDATE { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public string SUBMITTEDBYNM { get; set; }
        public string REMARKS { get; set; }

        public virtual ICollection<ASSOCIATIONENROLL> ASSOCIATIONENROLLs { get; set; }
        public virtual ICollection<BONDAPPLICATIONPROGRESS> BONDAPPLICATIONPROGRESSes { get; set; }
        public virtual BONDER BONDER { get; set; }
        public virtual ICollection<BONDERANNUALENTITLEMENT> BONDERANNUALENTITLEMENTs { get; set; }
    }
}
