//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BONDSUBCATEGORY
    {
        public BONDSUBCATEGORY()
        {
            this.BONDERs = new HashSet<BONDER>();
        }
    
        public short BSCATSLNO { get; set; }
        public string BSTYPECODE { get; set; }
        public string BSTYPECODEBG { get; set; }
        [Required]
        public string BSCATNAME { get; set; }
        public string BSCATNAMEBG { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual ICollection<BONDER> BONDERs { get; set; }
    }
}
