//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONDAPPLICATIONPROGRESS
    {
        public short PROGRESSSLNO { get; set; }
        public int BONDERSLNO { get; set; }
        public short BSNO { get; set; }
        public string READYFORAPP { get; set; }
        public string ACTION { get; set; }
        public Nullable<System.DateTime> ACTIONDATE { get; set; }
        public string ATTACHFILENM { get; set; }
        public string ATTACHFILEPATH { get; set; }
        public byte[] ATTACHFILEDATA { get; set; }
        public string REMARKS { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual BONDER BONDER { get; set; }
        public virtual BONDSTATU BONDSTATU { get; set; }
    }
}
