//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONDREGISTRATION
    {
        public short RGSLNO { get; set; }
        public int BONDERSLNO { get; set; }
        public short BSNO { get; set; }
        public string BONDLICENSENO { get; set; }
        public Nullable<short> BTYPESLNO { get; set; }
        public Nullable<short> BONDCIRCLESLNO { get; set; }
        public Nullable<decimal> FEEAMT { get; set; }
        public Nullable<decimal> VATPCT { get; set; }
        public Nullable<decimal> VATAMT { get; set; }
        public Nullable<decimal> TOTAMT { get; set; }
        public Nullable<System.DateTime> ISSUEDATE { get; set; }
        public Nullable<System.DateTime> EXPIRYDATE { get; set; }
        public Nullable<System.DateTime> RENEWALDATE { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public string AUTORENEWAL { get; set; }
    
        public virtual BONDCIRCLE BONDCIRCLE { get; set; }
        public virtual BONDER BONDER { get; set; }
        public virtual BONDTYPE BONDTYPE { get; set; }
    }
}
