//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONDERANNUALENTITLEMENTCOM
    {
        public short AESLNO { get; set; }
        public int BONDERSLNO { get; set; }
        public short MSLNO { get; set; }
        public string MEASUREMENT { get; set; }
        public string MSIZE { get; set; }
        public string WEIGHT { get; set; }
        public Nullable<short> MACHINESLNO { get; set; }
        public string MDESC { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual BONDER BONDER { get; set; }
        public virtual MATERIAL MATERIAL { get; set; }
        public virtual MACHINEINFORMATION MACHINEINFORMATION { get; set; }
    }
}
