//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class BONDAREA
    {
        [Key]
        public short BONDAREASLNO { get; set; }
        [Key, ForeignKey("BONDDIVISIONSLNO")] 
        public Nullable<short> BONDDIVISIONSLNO { get; set; }
        [Required]
        public string BONDAREAENAME { get; set; }
        public string BONDAREAENAMEBG { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
       
        public virtual BONDDIVISION BONDDIVISION { get; set; }
    }
}
