//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BONDER
    {
        public BONDER()
        {
            this.ASSOCIATIONENROLLs = new HashSet<ASSOCIATIONENROLL>();
            this.BACKTOBACKLCs = new HashSet<BACKTOBACKLC>();
            this.BONDAPPLICATIONPROGRESSes = new HashSet<BONDAPPLICATIONPROGRESS>();
            this.EXBONDs = new HashSet<EXBOND>();
            this.INBONDs = new HashSet<INBOND>();
            this.UPs = new HashSet<UP>();
            this.UPREQUESTs = new HashSet<UPREQUEST>();
            this.USERPERMISSIONs = new HashSet<USERPERMISSION>();
            this.BONDERANNUALENTITLEMENTs = new HashSet<BONDERANNUALENTITLEMENT>();
            this.BONDERLIENBANKs = new HashSet<BONDERLIENBANK>();
            this.BONDREGISTRATIONs = new HashSet<BONDREGISTRATION>();
            this.BONDSTATUS1 = new HashSet<BONDSTATU>();
            this.DOCUMENTATTACHMENTs = new HashSet<DOCUMENTATTACHMENT>();
            this.BONDERANNUALENTITLEMENTCOEDETs = new HashSet<BONDERANNUALENTITLEMENTCOEDET>();
            this.BONDERANNUALENTITLEMENTCOMs = new HashSet<BONDERANNUALENTITLEMENTCOM>();
        }
    
        public int BONDERSLNO { get; set; }
	    [Display(Name = "Bonder License No")]
        public string BONDLICENSENO { get; set; }
        public string BONDLICENSENOBG { get; set; }
        public string BONDSTATUS { get; set; }
        [Display(Name = "Bonder")]
        public string BONDERNAME { get; set; }
        public string BONDERNAMEBG { get; set; }
        public string HOLDINGNO { get; set; }
        public string ROADNO { get; set; }
        public string AREAVILLAGE { get; set; }
        public string MOWJA { get; set; }
        public string UNIONNAME { get; set; }
        public Nullable<short> BUPAZILASLNO { get; set; }
        public Nullable<short> BDISTRICTSLNO { get; set; }
        public string PSTATION { get; set; }
        public string WARD { get; set; }
        public string CITYPOURO { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string HOLDINGNOBG { get; set; }
        public string ROADNOBG { get; set; }
        public string AREAVILLAGEBG { get; set; }
        public string MOWJABG { get; set; }
        public string UNIONBG { get; set; }
        public string PSTATIONBG { get; set; }
        public string WARDBG { get; set; }
        public string CITYPOUROBG { get; set; }
        public string PHONEBG { get; set; }
        public string FAXBG { get; set; }
        public string MOBILEBG { get; set; }
        public string HOHOLDINGNO { get; set; }
        public string HOROADNO { get; set; }
        public string HOAREAVILLAGE { get; set; }
        public string HOMOWJA { get; set; }
        public string HOUNION { get; set; }
        public Nullable<short> HOUPAZILASLNO { get; set; }
        public Nullable<short> HODISTRICTSLNO { get; set; }
        public string HOPSTATION { get; set; }
        public string HOWARD { get; set; }
        public string HOCITYPOURO { get; set; }
        public string HOPHONE { get; set; }
        public string HOFAX { get; set; }
        public string HOMOBILE { get; set; }
        public string HOEMAIL { get; set; }
        public string HOHOLDINGNOBG { get; set; }
        public string HOROADNOBG { get; set; }
        public string HOAREAVILLAGEBG { get; set; }
        public string HOMOWJABG { get; set; }
        public string HOUNIONBG { get; set; }
        public string HOPSTATIONBG { get; set; }
        public string HOWARDBG { get; set; }
        public string HOCITYPOUROBG { get; set; }
        public string HOPHONEBG { get; set; }
        public string HOFAXBG { get; set; }
        public string HOMOBILEBG { get; set; }
        public string PREMESISSTATUS { get; set; }
        public Nullable<System.DateTime> HIREDATE { get; set; }
        public Nullable<System.DateTime> HIREEXPDATE { get; set; }
        public string HIREDEEDNO { get; set; }
        public Nullable<System.DateTime> OWNERSHIPDATE { get; set; }
        public string OWNERSHIPDOLILNO { get; set; }
        public string CSDAGNO { get; set; }
        public string RSDAGNO { get; set; }
        public string DEEDFILENM { get; set; }
        public byte[] DEEDFILEDATA { get; set; }
        public string DOLILFILENM { get; set; }
        public byte[] DOLILFILEDATA { get; set; }
        public string RENTVATCHALLANNO { get; set; }
        public string VCHALNFILENM { get; set; }
        public byte[] VCHALNFILEDATA { get; set; }
        public string BONDEDFAC { get; set; }
        public Nullable<short> BTYPESLNO { get; set; }
        public Nullable<short> BCATSLNO { get; set; }
        public Nullable<short> BSCATSLNO { get; set; }
        public string BONDFACPREV { get; set; }
        public string BONDFACPREVLICENNO { get; set; }
        public string BONDFACPREVLICENNOBG { get; set; }
        public string OWNERCATEGORY { get; set; }
        public Nullable<decimal> TOTFACLENG { get; set; }
        public Nullable<decimal> TOTFACWIDTH { get; set; }
        public Nullable<decimal> TOTRMWHLENG { get; set; }
        public Nullable<decimal> TOTRMWHWIDTH { get; set; }
        public Nullable<decimal> TOTRMWHHEIGHT { get; set; }
        public Nullable<decimal> TOTFGWHLENG { get; set; }
        public Nullable<decimal> TOTFGWHWIDTH { get; set; }
        public Nullable<decimal> TOTFGWHHEIGHT { get; set; }
        public string AUTHORIZEDSIGNAME { get; set; }
        public string AUTHORIZEDSIGNAMEBG { get; set; }
        public string INITIALAUTHSIGFILENM { get; set; }
        public byte[] INITIALAUTHSIGFILEDATA { get; set; }
        public string PHOTOFILENM { get; set; }
        public byte[] PHOTOFILEDATA { get; set; }
        public string DECLARFILENM { get; set; }
        public byte[] DECLARFILEDATA { get; set; }
        public string DECLARSIGFILENM { get; set; }
        public byte[] DECLARSIGFILEDATA { get; set; }
        public string DECLARSEALFILENM { get; set; }
        public byte[] DECLARSEALFILEDATA { get; set; }
        public Nullable<short> DECLARDESSLNO { get; set; }
        public Nullable<System.DateTime> DECLARDATE { get; set; }
        public string REMARKS { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public string DECLARNMBLOCK { get; set; }
        public string ADDRESS { get; set; }
        public string COADDRESS { get; set; }
    
        public virtual ICollection<ASSOCIATIONENROLL> ASSOCIATIONENROLLs { get; set; }
        public virtual ICollection<BACKTOBACKLC> BACKTOBACKLCs { get; set; }
        public virtual ICollection<BONDAPPLICATIONPROGRESS> BONDAPPLICATIONPROGRESSes { get; set; }
        public virtual BONDCATEGORY BONDCATEGORY { get; set; }
        public virtual ICollection<EXBOND> EXBONDs { get; set; }
        public virtual ICollection<INBOND> INBONDs { get; set; }
        public virtual ICollection<UP> UPs { get; set; }
        public virtual ICollection<UPREQUEST> UPREQUESTs { get; set; }
        public virtual ICollection<USERPERMISSION> USERPERMISSIONs { get; set; }
        public virtual UPAZILA UPAZILA { get; set; }
        public virtual ICollection<BONDERANNUALENTITLEMENT> BONDERANNUALENTITLEMENTs { get; set; }
        public virtual ICollection<BONDERLIENBANK> BONDERLIENBANKs { get; set; }
        public virtual ICollection<BONDREGISTRATION> BONDREGISTRATIONs { get; set; }
        public virtual ICollection<BONDSTATU> BONDSTATUS1 { get; set; }
        public virtual ICollection<DOCUMENTATTACHMENT> DOCUMENTATTACHMENTs { get; set; }
        public virtual DISTRICT DISTRICT { get; set; }
        public virtual ICollection<BONDERANNUALENTITLEMENTCOEDET> BONDERANNUALENTITLEMENTCOEDETs { get; set; }
        public virtual ICollection<BONDERANNUALENTITLEMENTCOM> BONDERANNUALENTITLEMENTCOMs { get; set; }
        public virtual UPAZILA UPAZILA1 { get; set; }
        public virtual DISTRICT DISTRICT1 { get; set; }
        public virtual BONDTYPE BONDTYPE { get; set; }
        public virtual BONDSUBCATEGORY BONDSUBCATEGORY { get; set; }
        public virtual DESIGNATION DESIGNATION { get; set; }
    }
}
