//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONDERANNUALENTITLEMENTCOEDET
    {
        public short AESLNO { get; set; }
        public int BONDERSLNO { get; set; }
        public short MSLNO { get; set; }
        public short RMSLNO { get; set; }
        public Nullable<decimal> GROSSQT { get; set; }
        public Nullable<decimal> WASTAGEQT { get; set; }
        public Nullable<decimal> SHRINKAGEQT { get; set; }
        public Nullable<decimal> NETQT { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual BONDER BONDER { get; set; }
        public virtual MATERIAL MATERIAL { get; set; }
        public virtual MATERIAL MATERIAL1 { get; set; }
    }
}
