//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class COUNTRY
    {
        public COUNTRY()
        {
            this.INSTALLEDMACHINEINFOes = new HashSet<INSTALLEDMACHINEINFO>();
            this.DISTRICTs = new HashSet<DISTRICT>();
            this.OFFICEs = new HashSet<OFFICE>();
        }
    
        public short COUNTRYSLNO { get; set; }
        public string COUNTRYCODE { get; set; }
        public string COUNTRYCODEBG { get; set; }
        [Required]
        public string COUNTRYNAME { get; set; }
        public string COUNTRYNAMEBG { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual ICollection<INSTALLEDMACHINEINFO> INSTALLEDMACHINEINFOes { get; set; }
        public virtual ICollection<DISTRICT> DISTRICTs { get; set; }
        public virtual ICollection<OFFICE> OFFICEs { get; set; }
    }
}
