//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CURRENCY
    {
        public short CURRSLNO { get; set; }
        public string CURRENCYCODE { get; set; }
        public string CURRENCYSNM { get; set; }
        public string CURRENCYSNMBG { get; set; }
        [Required]
        public string CURRENCYNAME { get; set; }
        public string CURRENCYNAMEBG { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    }
}
