//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DESIGNATION
    {
        public DESIGNATION()
        {
            this.BONDERs = new HashSet<BONDER>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.OWNERINFOes = new HashSet<OWNERINFO>();
            this.OFFICEs = new HashSet<OFFICE>();
            this.OWNERASSOCIATEBUSINESSes = new HashSet<OWNERASSOCIATEBUSINESS>();
        }
    
        public short DESSLNO { get; set; }
        public string DESCODE { get; set; }
        public string DESCODEBG { get; set; }
        [Required]
        public string DESNAME { get; set; }
        public string DESNAMEBG { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual ICollection<BONDER> BONDERs { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual ICollection<OWNERINFO> OWNERINFOes { get; set; }
        public virtual ICollection<OFFICE> OFFICEs { get; set; }
        public virtual ICollection<OWNERASSOCIATEBUSINESS> OWNERASSOCIATEBUSINESSes { get; set; }
    }
}
