//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.USERPERMISSIONs = new HashSet<USERPERMISSION>();
        }
    
        public short EMPLOYEESLNO { get; set; }
        public Nullable<short> OFFICESLNO { get; set; }
        public string EMPLOYEENAME { get; set; }
        public string EMPLOYEENAMEBG { get; set; }
        public string PHOTOFILENM { get; set; }
        public byte[] PHOTOFILEDATA { get; set; }
        public Nullable<short> DESSLNO { get; set; }
        public string PHONE { get; set; }
        public string PHONEBG { get; set; }
        public string MOBILE { get; set; }
        public string MOBILEBG { get; set; }
        public string EMAIL { get; set; }
        public string STATUS { get; set; }
        public string EMPLOYEETYPE { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual DESIGNATION DESIGNATION { get; set; }
        public virtual ICollection<USERPERMISSION> USERPERMISSIONs { get; set; }
        public virtual OFFICE OFFICE { get; set; }
    }
}
