//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EXBOND
    {
        public EXBOND()
        {
            this.EXBONDBACKTOBACKs = new HashSet<EXBONDBACKTOBACK>();
            this.UPEXBONDLISTs = new HashSet<UPEXBONDLIST>();
        }
    
        [Display(Name = "Exbond Id")]
        public short ID { get; set; }
        [Display(Name = "Description")]
        public string DESCRIPTION { get; set; }
        public int BONDERID { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
    
        public virtual ICollection<EXBONDBACKTOBACK> EXBONDBACKTOBACKs { get; set; }
        public virtual ICollection<UPEXBONDLIST> UPEXBONDLISTs { get; set; }
        public virtual BONDER BONDER { get; set; }

        public bool IsSelected { get; set; }
    }
}
