//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class INBONDRAWMATERIAL
    {
        public short ID { get; set; }
        [Display(Name = "Raw Material Code")]
        [Required]
        public short RAWMATERIALCODE { get; set; }
        [Display(Name = "Product Qty")]
        [Required(ErrorMessage = "Product Qty  is required.")]
       
        public decimal PRODUCTQUANTITY { get; set; }
        [Display(Name = "Quantity Unit")]
        [Required(ErrorMessage = "Quantity Unit  is required.")]
        public string QUANTITYUNIT { get; set; }
        [Display(Name = "Product Cost")]
        [Required(ErrorMessage = "Product Cost  is required.")]
       
        public decimal PRODUCTCOST { get; set; }
        [Display(Name = "Cost Unit")]
        [Required(ErrorMessage = "Cost Unit  is required.")]
        public string COSTUNIT { get; set; }
        public short INBONDID { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
    
        public virtual INBOND INBOND { get; set; }
        public virtual MATERIAL MATERIAL { get; set; }
    }
}
