//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class INBOND
    {
        public INBOND()
        {
            this.INBONDRAWMATERIALs = new List<INBONDRAWMATERIAL>();
        }

        [Display(Name = "Inbond Id")]
        public short ID { get; set; }
        [Required(ErrorMessage = "Please enter a LC no.")]
        [Display(Name = "LC No")]
        public string LCNUMBER { get; set; }
        [Display(Name = "LC Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime LCDATE { get; set; }
        [Display(Name = "BOE No")]
        [Required(ErrorMessage = "Please enter a BOE  no.")]

        public string BOENUMBER { get; set; }
        [Display(Name = "BOE Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime BOEDATE { get; set; }
        [Display(Name = "Bonder Id")]
        public int BONDERID { get; set; }
        [Display(Name = "Created By")]
        public string CREATEDBY { get; set; }
        [Display(Name = "Created Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        [Display(Name = "Modified By")]
        public string MODIFIEDBY { get; set; }
        [Display(Name = "Modified Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }

        public virtual BONDER BONDER { get; set; }

        public virtual IList<INBONDRAWMATERIAL> INBONDRAWMATERIALs { get; set; }
        
       
        
    }
}
