//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTALLEDMACHINEINFO
    {
        public short MACHINESLNO { get; set; }
        public int BONDERSLNO { get; set; }
        public Nullable<System.DateTime> DATEOFINSTALL { get; set; }
        public string BENO { get; set; }
        public string BENOBG { get; set; }
        public Nullable<System.DateTime> BENODATE { get; set; }
        public string VATCHNO { get; set; }
        public string VATCHNOBG { get; set; }
        public Nullable<System.DateTime> VATCHNODATE { get; set; }
        public string BLNO { get; set; }
        public string BLNOBG { get; set; }
        public Nullable<System.DateTime> BLNODATE { get; set; }
        public string INVOICENO { get; set; }
        public string INVOICENOBG { get; set; }
        public Nullable<System.DateTime> INVOICENODATE { get; set; }
        public string LCNO { get; set; }
        public string LCNOBG { get; set; }
        public Nullable<System.DateTime> LCNODATE { get; set; }
        public Nullable<decimal> MACHINEQTY { get; set; }
        public string MACHINETYPE { get; set; }
        public string PROCUREMENTTYPE { get; set; }
        public string INDEMNITYBOND { get; set; }
        public string INDEMNITYUNDERTKNO { get; set; }
        public string INDEMNITYUNDERTKNOBG { get; set; }
        public Nullable<System.DateTime> INDEMNITYUNDERTKDT { get; set; }
        public string CASHCHALNVOUCHNO { get; set; }
        public string CASHCHALNVOUCHNOBG { get; set; }
        public Nullable<System.DateTime> CASHCHALNVOUCHDT { get; set; }
        public Nullable<System.DateTime> DUERELEASDT { get; set; }
        public Nullable<System.DateTime> ACTRELEASDT { get; set; }
        public string LOCALPURCLEARENCEFROM { get; set; }
        public string LOCALPURCLEARENCEFROMBG { get; set; }
        public string LOCALPURCLEARENCENO { get; set; }
        public string LOCALPURCLEARENCENOBG { get; set; }
        public Nullable<System.DateTime> LOCALPURCLEARENCEDT { get; set; }
        public string LOCALPURPERMISSIONFROMCBC { get; set; }
        public Nullable<System.DateTime> LOCALPURPERMISSIONFROMCBCDT { get; set; }
        public Nullable<short> TRANSFERLIENBANK { get; set; }
        public string TRANSFERLIENBANKNOCNO { get; set; }
        public string TRANSFERLIENBANKNOCNOBG { get; set; }
        public Nullable<System.DateTime> TRANSFERLIENBANKDT { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESCRIPTIONBG { get; set; }
        public string MANUFACTUREYEAR { get; set; }
        public string MANUFACTUREYEARBG { get; set; }
        public Nullable<short> COUNTRYSLNO { get; set; }
        public Nullable<short> MODELSLNO { get; set; }
    
        public virtual BANKBRANCH BANKBRANCH { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual MODEL MODEL { get; set; }
        public virtual MACHINEINFORMATION MACHINEINFORMATION { get; set; }
    }
}
