//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACHINEINFORMATION
    {
        public MACHINEINFORMATION()
        {
            this.BONDERANNUALENTITLEMENTCOMs = new HashSet<BONDERANNUALENTITLEMENTCOM>();
            this.INSTALLEDMACHINEINFOes = new HashSet<INSTALLEDMACHINEINFO>();
            this.MODELs = new HashSet<MODEL>();
            this.PRODCAPACITYMACHINEWISEMs = new HashSet<PRODCAPACITYMACHINEWISEM>();
            this.PRODCAPACITYMACHINEWISEDETs = new HashSet<PRODCAPACITYMACHINEWISEDET>();
        }
    
        public short MACHINESLNO { get; set; }
        public string MODELNM { get; set; }
        public string MODELNMBG { get; set; }
        public string REMARKS { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public string BRAND_NAME { get; set; }
    
        public virtual ICollection<BONDERANNUALENTITLEMENTCOM> BONDERANNUALENTITLEMENTCOMs { get; set; }
        public virtual ICollection<INSTALLEDMACHINEINFO> INSTALLEDMACHINEINFOes { get; set; }
        public virtual ICollection<MODEL> MODELs { get; set; }
        public virtual ICollection<PRODCAPACITYMACHINEWISEM> PRODCAPACITYMACHINEWISEMs { get; set; }
        public virtual ICollection<PRODCAPACITYMACHINEWISEDET> PRODCAPACITYMACHINEWISEDETs { get; set; }
    }
}
