//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MATERIALSGROUP
    {
        public MATERIALSGROUP()
        {
            this.MATERIALS = new HashSet<MATERIAL>();
        }
    
        public short MGSLNO { get; set; }
        public string MGROUPCODE { get; set; }
        public string MGROUPCODEBG { get; set; }
        [Required]
        public string MGROUPCODENAME { get; set; }
        public string MGROUPCODENAMEBG { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual ICollection<MATERIAL> MATERIALS { get; set; }
    }
}
