//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEASUREMENTUNITCONVERSION
    {
        public short CONVSLNO { get; set; }
        public Nullable<short> MUSLNO1 { get; set; }
        public Nullable<short> MUSLNO2 { get; set; }
        public Nullable<decimal> CONVVALUE { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual MEASUREMENTUNIT MEASUREMENTUNIT { get; set; }
        public virtual MEASUREMENTUNIT MEASUREMENTUNIT1 { get; set; }
    }
}
