//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class OFFICE
    {
        public OFFICE()
        {
            this.ASSOCIATIONENROLLs = new HashSet<ASSOCIATIONENROLL>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
        }
    
        public short OFFICESLNO { get; set; }
        [Required]
        public string OFFICENAME { get; set; }
        public string OFFICENAMEBG { get; set; }
        public string OFFICESNAME { get; set; }
        public string OFFICESNAMEBG { get; set; }
        public string ADDRESS { get; set; }
        public string ADDRESSBG { get; set; }
        public Nullable<short> COUNTRYSLNO { get; set; }
        public Nullable<short> DISTRICTSLNO { get; set; }
        public string CONTACTPERSON { get; set; }
        public string CONTACTPERSONBG { get; set; }
        public Nullable<short> DESSLNO { get; set; }
        public string MOBILENO { get; set; }
        public string MOBILENOBG { get; set; }
        public string PHONE { get; set; }
        public string PHONEBG { get; set; }
        public string FAX { get; set; }
        public string FAXBG { get; set; }
        [EmailAddress(ErrorMessage = "Wrong Email Format")]
        public string EMAIL { get; set; }
        public string WEB { get; set; }
        public string OFFICETYPE { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual ICollection<ASSOCIATIONENROLL> ASSOCIATIONENROLLs { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual DESIGNATION DESIGNATION { get; set; }
        public virtual DISTRICT DISTRICT { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
    }
}
