//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWNERINFO
    {
        public short OWNERSLNO { get; set; }
        public int BONDERSLNO { get; set; }
        public Nullable<short> DESSLNO { get; set; }
        public string OWNERNAME { get; set; }
        public string OWNERNAMEBG { get; set; }
        public string OWNERFHNAME { get; set; }
        public string OWNERFHNAMEBG { get; set; }
        public string OWNERPERADDRESS { get; set; }
        public string OWNERPERADDRESSBG { get; set; }
        public string OWNERPRSADDRESS { get; set; }
        public string OWNERPRSADDRESSBG { get; set; }
        public string OWNERCONTACTNO { get; set; }
        public string OWNERCONTACTNOBG { get; set; }
        public string OWNERRESPHONE { get; set; }
        public string OWNERRESPHONEBG { get; set; }
        public string OWNERMOBPHONE { get; set; }
        public string OWNERMOBPHONEBG { get; set; }
        public string TINNO { get; set; }
        public Nullable<System.DateTime> TINISSDT { get; set; }
        public string PASSPORTNO { get; set; }
        public Nullable<short> PASSDISTRICTSLNO { get; set; }
        public Nullable<System.DateTime> PASSISSUEDT { get; set; }
        public Nullable<System.DateTime> PASSEXPDT { get; set; }
        public string NATIONALITY { get; set; }
        public string NATIONALITYBG { get; set; }
        public string NATIONALZIDNO { get; set; }
        public string SIGNATUREFILENM { get; set; }
        public string SIGNATUREFILEPATH { get; set; }
        public byte[] SIGNATUREFILEDATA { get; set; }
        public string PHOTOFILENM { get; set; }
        public string PHOTOFILEPATH { get; set; }
        public byte[] PHOTOFILEDATA { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual DESIGNATION DESIGNATION { get; set; }
        public virtual DISTRICT DISTRICT { get; set; }
    }
}
