//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWNERASSOCIATEBUSINESS
    {
        public short ASSOCIATESLNO { get; set; }
        public short OWNERSLNO { get; set; }
        public int BONDERSLNO { get; set; }
        public string ASSOBUSINESSNAME { get; set; }
        public string ASSOBUSINESSNAMEBG { get; set; }
        public string ASSOBUSINESSADDRESS { get; set; }
        public string ASSOBUSINESSADDRESSBG { get; set; }
        public string TINASSOBUSINESS { get; set; }
        public string TINASSOBUSINESSBG { get; set; }
        public Nullable<System.DateTime> TINDATE { get; set; }
        public string BINASSOBUSINESS { get; set; }
        public string BINASSOBUSINESSBG { get; set; }
        public Nullable<System.DateTime> BINDATE { get; set; }
        public string BUSINESSNATURE { get; set; }
        public string BUSINESSNATUREBG { get; set; }
        public string BUSINESSPOS { get; set; }
        public string BUSINESSPOSBG { get; set; }
        public string BUSINESSSHARE { get; set; }
        public string BUSINESSSHAREBG { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<short> OWNERDESSLNO { get; set; }
        public string OWNERNAME { get; set; }
        public string OWNERTINNO { get; set; }
        public Nullable<System.DateTime> OWNERTINISSDT { get; set; }
        public string OWNERNATIONALZIDNO { get; set; }
    
        public virtual DESIGNATION DESIGNATION { get; set; }
    }
}
