//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODCAPACITYMACHINEWISEDET
    {
        public short FPSLNO { get; set; }
        public int BONDERSLNO { get; set; }
        public short MACHINESLNO { get; set; }
        public Nullable<short> MACHINEQTY { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public string MACHINETYPE { get; set; }
    
        public virtual MACHINEINFORMATION MACHINEINFORMATION { get; set; }
        public virtual PRODCAPACITYMACHINEWISEM PRODCAPACITYMACHINEWISEM { get; set; }
    }
}
