//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RAWMATERIAL
    {
        public short ID { get; set; }

        [Display(Name = "Raw Material Name")]
        public short RAWMATERIALCODE { get; set; }

        [Display(Name = "Quantity")]
        public decimal QUANTITY { get; set; }
        
        [Display(Name = "Unit")]
        public string UNIT { get; set; }
        
        [Display(Name = "Misuse %")]
        public decimal PERMITTEDWASTE { get; set; }
        public short PRODUCTID { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
    
        public virtual BACKTOBACKPRODUCT BACKTOBACKPRODUCT { get; set; }
        public virtual MATERIAL MATERIAL { get; set; }
    }
}
