//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UP
    {
        public UP()
        {
            this.UPREQUESTLISTs = new HashSet<UPREQUESTLIST>();
        }
    
        public short ID { get; set; }
        public int BONDERID { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public string UPNO { get; set; }
    
        public virtual ICollection<UPREQUESTLIST> UPREQUESTLISTs { get; set; }
        public virtual BONDER BONDER { get; set; }
    }
}
