//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UPAZILA
    {
        public UPAZILA()
        {
            this.BONDERs = new HashSet<BONDER>();
            this.BONDERs1 = new HashSet<BONDER>();
        }
    
        public short UPAZILASLNO { get; set; }
        public Nullable<short> DISTRICTSLNO { get; set; }
        [Required]
        public string UPAZILANAME { get; set; }
        public string UPAZILANAMEBG { get; set; }
        public string INPUTBY { get; set; }
        public Nullable<System.DateTime> INPUTDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual ICollection<BONDER> BONDERs { get; set; }
        public virtual ICollection<BONDER> BONDERs1 { get; set; }
        public virtual DISTRICT DISTRICT { get; set; }
    }
}
