//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPEXBONDLIST
    {
        public short EXBONDID { get; set; }
        public short UPREQUESTID { get; set; }
        public short ID { get; set; }
    
        public virtual UPREQUEST UPREQUEST { get; set; }
        public virtual EXBOND EXBOND { get; set; }
    }
}
