//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSPhase2Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UPREQUEST
    {
        public UPREQUEST()
        {
            this.ATTACHMENTs = new List<ATTACHMENT>();
            this.UPEXBONDLISTs = new List<UPEXBONDLIST>();
            this.UPREQUESTLISTs = new List<UPREQUESTLIST>();
        }
        [Display(Name = "Request ID")]
        public short ID { get; set; }
         [Display(Name = "Status")]
        public short STATUS { get; set; }
       [Display(Name = "Requested By")]
        public string CREATEDBY { get; set; }
        [Display(Name = "Requested Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string MODIFIEDBY { get; set; }
        [Display(Name = "Modified Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }

        public int BONDERID { get; set; }

        public string REJECTCOMMENT { get; set; }
    
        public virtual IList<ATTACHMENT> ATTACHMENTs { get; set; }
        public virtual BONDER BONDER { get; set; }
        public virtual IList<UPEXBONDLIST> UPEXBONDLISTs { get; set; }
        public virtual IList<UPREQUESTLIST> UPREQUESTLISTs { get; set; }

        public bool IsSelected { get; set; }
    }
}
